name: prepare-release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    name: Prepare release
    if: github.repository == 'skyclouds2001/template-sky'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.1.3
        with:
          release-type: node
